### ISSUE TITLE
Vertalingen voor de actie

### ISSUE THREAD

**Issue by alfamongrel** [ActivismeBE-archive/ACTIE-ontbinding-nato#18]
gelieve de mogelijk te maken om de petitie meertalig te maken 
we verwachten een vertaling van Peter teryn

**Comment by Tjoosten** [comment]
**UPDATE:**
-  Aparte branch (`patch-18`) is voor dit ticket aangemaakt in github. 
- Milestone `Server-Deployment-2` is toegewijd aan alleen de vertaling van de petitie.

**Comment by Tjoosten** [comment]
@alfamongrel de disclaimer moet ook vertaald worden.

**Comment by Tjoosten** [comment]
**Update: -> @alfamongrel** Peter Terryn geprobeerd te bereiken voor de tekst maar geen gehoor.
