### ISSUE TITLE
een bezoekerscounter implementer en een share counter

### ISSUE THREAD

**Issue by alfamongrel** [ActivismeBE-archive/ACTIE-ontbinding-nato#19]
wel rekening houden een bezoekersteller en een getekende teller en bij het delen een deel teller is om dat ik nu statistieken bij hou voor de toekomst aangezien we vzw gaan

**Comment by alfamongrel** [comment]
gelieve dit te bekijken indien mogelijk

**Comment by Tjoosten** [comment]
@TeppersBen Hoe zou jij dit design gewijs oplossen? 

@Alfamongrel Bezoekers kan ik laten uitmeten door google Analytics. En Share gaat het design breken vrees ik

**Comment by Tjoosten** [comment]
Share statistiek kan worden opgehaald door opengraph van facebook. Vandaar dat ik opteer deze niet te implementeren in de applicatie zelf.
